### ISSUE TITLE
thamos advise adds a duplicate index/source

### ISSUE THREAD

**Issue by codificat** [thoth-station/support#237]
**Describe the bug**

When I request a `thamos advise` based on a `Pipfile` that has a `[[source]]` pointing to PyPI with a name other than "pypi-org-simple", the result of the advise modifies the `Pipfile` adding a (duplicate) `[[source]]` entry for PyPI

**To Reproduce**
1. Create a Pipfile that contains a PyPI source with a name other than "pypi-org-simple". For example (note the `name`):
``` toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
scikit-learn = "*"

[dev-packages]

[requires]
python_version = "3.8"

[thoth]
disable_index_adjustment = false
```

2. Configure `thamos`
3. Run `thamos advise`

**Expected behavior**
The `[[source]]` section in `Pipfile` remains untouched

**Actual behavior**

After the advise request finishes, the `Pipfile` looks like this:

``` toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi-org-simple"

[packages]
scikit-learn = "*"
[...]
```
