### ISSUE TITLE
import plotly fails with Requests dependency 'urllib3' must be version >= 1.21.1, < 1.22! after thamos advise

### ISSUE THREAD

**Issue by pacospace** [thoth-station/support#5]
**Describe the bug**

**To Reproduce**
1. thamos advise for 
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi-org-simple"

[packages]
pandas = "*"
plotly = "*"

[dev-packages]

[requires]
python_version = "3.8"

```
adviser id: adviser-210708125600-14726dc7e3be

Stack was provided successfully: https://gist.github.com/pacospace/146b289cff4f5ad6bdc10c7be6ed9f01

**Expected behavior**
`import plotly` works successfully,

It requires a new prescription Sieve probably.

**Screenshots**
![Screenshot from 2021-07-08 15-21-21](https://user-images.githubusercontent.com/27498679/124928921-5411b300-e000-11eb-88a4-16508f0c8aac.png)

**Additional context**

**Comment by fridex** [comment]
This is strange as requests state version range requirements on `urllib3<1.22,>=1.21.1` as reported in the traceback. I wonder how this resolution ended with the specified urllib3.

Locally, I cannot reproduce this, will wait until the zero cluster is up again. A reproducer for this should be `Pipfile` stating (which should fail to resolve given versions pinned):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi-org-simple"

[packages]
requests = "==2.17.1"
urllib3 = "==1.25.10"
```
